name: Simple Docker Action
description: Prints a message and the provided input
# 定义 action 的input参数
inputs:
  # 当 GitHub Actions 运行这个 Docker-based Action 时，会将所有的 inputs 参数转换为环境变量，
  # 并作为 Docker 容器的运行参数传递进去：inputs.<input_name> 会映射为环境变量 INPUT_<INPUT_NAME>
  # 也就是在容器内：name -> INPUT_NAME
  name:
    description: The greeting name to print
    required: true
    default: Hello, World!

# 定义action的output参数
outputs:
  # 这个 Action 需要向 #GITHUB_OUTPUT 这个文件里写入 docker-action-output=value 的形式，
  # 这个文件会被 GitHub Actions自动解析出来，便于workflow后续step可以访问这个docker-action-output
  docker-action-output:
    description: The custom output from the action

runs:
  # 指定了运行时环境，这里为 "docker"，说明这个 Action 是基于 Docker 容器运行的。
  using: "docker"
  # 指定了一个 Docker 镜像，这里为 "Dockerfile"，表示使用当前目录下的 Dockerfile
  # 定义内容来构建 Docker 环境，并运行 Action 的任务。
  image: "Dockerfile"